# Generated by Django 5.2.5 on 2025-09-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0004_vacancyreq_whois'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
