# Generated by Django 5.2.5 on 2025-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0005_delete_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('blocked', models.BooleanField(default=False)),
                ('in_params', models.JSONField()),
                ('out_params', models.JSONField()),
            ],
        ),
    ]
