# Generated by Django 5.2.5 on 2025-09-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0006_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hyperlink',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rawtext',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skydev_app.vacancy'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contacts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='foreign_langs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ищет работу'), (2, 'Рассматривает предложения'), (3, 'Не готов общаться')], null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='town',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='allow_trip',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Редко'), (3, 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='contract_type',
            field=models.IntegerField(choices=[(1, 'Бессрочный'), (2, 'Срочный'), (3, 'По совместительству'), (4, 'ГПХ')], null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='emp_type',
            field=models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Временная занятость'), (4, 'Проектная деятельность')], null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='software_knowledges',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='software_skills',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='specs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='work_sced',
            field=models.IntegerField(choices=[(1, 'Офис'), (2, 'Гибрид'), (3, 'Удаленная работа')], null=True),
        ),
    ]
