# Generated by Django 5.2.5 on 2025-09-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0007_candidate_hyperlink_candidate_rawtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
