# Generated by Django 5.2.5 on 2025-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0008_vacancy_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='allow_trip',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Редко'), (3, 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ann_premium',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='change_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contract_type',
            field=models.IntegerField(choices=[(1, 'Бессрочный'), (2, 'Срочный'), (3, 'По совместительству'), (4, 'ГПХ')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='edu_level',
            field=models.IntegerField(choices=[(1, 'Б/о'), (2, 'Среднее'), (3, 'Средне-специальное'), (4, 'Высшее')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='emp_type',
            field=models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Временная занятость'), (4, 'Проектная деятельность')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='foreign_langs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='premium_type',
            field=models.IntegerField(choices=[(1, 'Месячное'), (2, 'Квартальное'), (3, 'Годовое')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='software_knowledges',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='software_skills',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(1, 'Открыта'), (2, 'Приостановлена'), (3, 'Отменена'), (4, 'Закрыта')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='town',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_sced',
            field=models.IntegerField(choices=[(1, 'Офис'), (2, 'Гибрид'), (3, 'Удаленная работа')], null=True),
        ),
    ]
