# Generated by Django 5.2.5 on 2025-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0009_alter_vacancy_address_alter_vacancy_allow_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='rawtext',
            field=models.TextField(null=True),
        ),
    ]
