# Generated by Django 5.2.5 on 2025-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0010_empprofile_rawtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='similarity_score',
            field=models.FloatField(null=True),
        ),
    ]
