# Generated by Django 5.2.5 on 2025-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0011_empprofile_similarity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('caption', models.TextField()),
                ('value', models.FloatField()),
                ('ordernum', models.IntegerField()),
            ],
        ),
    ]
