# Generated by Django 5.2.5 on 2025-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0012_statparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='similarity_score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
